SisCoV/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SisCoV.Models;
using SistAL.Models.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SisCoV.Controllers
{
    public class PedidoController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public PedidoController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CategoriaPedidos()
        {
            return View();
        }

        public IActionResult ExibirLanchesPedidos() 
        {
            return View();
        }
        public IActionResult ExibirPorcoesPedidos()
        {
            return View();
        }
        public IActionResult ExibirBebidasPedidos()
        {
            return View();
        }
        public IActionResult LanchesPedidos()
        {
            try
            {
                ExibirPedidos exibirPedidos = new ExibirPedidos();
                var _listaLanchesPedidos = exibirPedidos.ExibirFilaLanchesPedidos();


                ConverterObjectToJson converterObjtectToJson = new ConverterObjectToJson();
                var _jsonListaLanchesPedidos = converterObjtectToJson.ConverteObjectParaJSon(_listaLanchesPedidos);

                return Ok(_jsonListaLanchesPedidos);


            }
            catch (Exception)
            {

                throw;
            }
            
        }
       
        public IActionResult CriarPedido(int idMesa, string NomeCliente)
        {
            try
            {
                string Resposta = string.Empty;
                Mesa mesa = new Mesa();
                var _statusMesa = mesa.VerificarStatusMesa(idMesa);

                ConverterObjectToJson converterObjtectToJson = new ConverterObjectToJson();
                if (_statusMesa) 
                {
                    Resposta = "Não é possivel criar pedido em mesa ocupada, escolha outra mesa, por favor!";
                    var _jsonStatusMesa = converterObjtectToJson.ConverteObjectParaJSon(_statusMesa);
                    return Ok(_jsonStatusMesa);
                }
                else
                {
                    Pedido pedido = new Pedido(0, idMesa, 1, 0);
                    pedido.CadastrarPedido(pedido);
                    return Redirect("Pedido/CategoriaPedidos");
                }
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public IActionResult FecharPedido(long IdPedido, int IdMesa, int TipoPagamento)
        {
            try
            {
                Pedido pedido = new Pedido(IdPedido, IdMesa, 1,TipoPagamento);
                pedido.FecharPedido(pedido);
            }
            catch (Exception ex)
            {

                throw;
            }
            return Ok();
        }

        public IActionResult VerificarStatusMesa(int Id)
        {
            try
            {
                Mesa mesa = new Mesa();
                var _statusMesa = mesa.VerificarStatusMesa(Id);

                ConverterObjectToJson converterObjtectToJson = new ConverterObjectToJson();
                var _jsonStatusMesa = converterObjtectToJson.ConverteObjectParaJSon(_statusMesa);

                return Ok(_jsonStatusMesa);
            }
            catch (Exception)
            {

                throw;
            }
            

        }

        public IActionResult ItemPedido()
        {
            try
            {
                ItemPedido itemPedido = new ItemPedido();
                var _listItensPedido = itemPedido.BuscarItemPedido(1);

                ConverterObjectToJson converterObjtectToJson = new ConverterObjectToJson();
                var _jsonListItensPedido = converterObjtectToJson.ConverteObjectParaJSon(_listItensPedido);

                return Ok(_jsonListItensPedido);
            }
            catch (Exception)
            {

                throw;
            }
           
        }

        public IActionResult GetTipoPagamento()
        {
            try
            {
                TipoPagamento tipoPagamento = new TipoPagamento();
                var _listTipoPagamento = tipoPagamento.BuscarTipoPagamento();

                ConverterObjectToJson converterObjtectToJson = new ConverterObjectToJson();
                var _jsonListTipoPagamento = converterObjtectToJson.ConverteObjectParaJSon(_listTipoPagamento);

                return Ok(_jsonListTipoPagamento);
            }
            catch (Exception)
            {

                throw;
            }

        }

        public IActionResult GetIdPedido(int idMesa)
        {
            try
            {
                Pedido _pedido = new Pedido();
                var _idPedido = _pedido.RetornaIdPedido(idMesa);

                ConverterObjectToJson converterObjtectToJson = new ConverterObjectToJson();
                var _jsonListTipoPagamento = converterObjtectToJson.ConverteObjectParaJSon(_idPedido);

                return Ok(_jsonListTipoPagamento);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SisCoV/Views/Shared/_Footer.cshtml
<footer class="border-top footer text-muted fixed-bottom bg-white">
    <div class="container">
        &copy; SistAL 2021 - Desenvolvido por ICA Automação - Todos Direitos Reservados - @Html.ActionLink("Privacidade", "Privacy", "Home")
    </div>
</footer>

SisCoV/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SisCoV</title>
    <link rel="stylesheet" type="text/css" href="~/css/all.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/principal.css" />
</head>
<body>
    @{
        var username = HttpContextAccessor.HttpContext.Session.GetString("Username");
    }

    @if (username != null)
    {
        @Html.Partial("_MenuSuperior")
        @Html.Partial("_SideBar")
        <div class="container" style="padding-top: 70px; border-left:100px;">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        @Html.Partial("_Footer")
    }
    else
    {
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SisCoV/Views/Shared/_MenuSuperior.cshtml
<input type="checkbox" id="check" />
<header>
    <label for="check">
        <i class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
        <h3>Sistema de Pedidos</h3>
    </div>
    <div class="rigth_area">
        <a href="/Home/Logout" class="logout_btn">Logout</a>
        <img src="~/img/logoICA" class="imgLogoICA" />
    </div>
</header>

SisCoV/Views/Shared/_SideBar.cshtml
<link rel="stylesheet" type="text/css" href="~/css/awesomeall.min.css" />
<div class="sidebar">
    <center>
        <img class="profile_image" src="~/img/logoArcelorMittal/ArcelorMittal.png" alt="" />
    </center>
    <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-calculator"><span>&nbsp; Mesas</span></i></a>
    <a asp-area="" asp-controller="Pedido" asp-action="CategoriaPedidos"><i class="fas fa-database"><span>&nbsp;Pedidos</span></i></a>
    <a asp-area="" asp-controller="Pedido" asp-action="ExibirLanchesPedidos"><i class="fas fa-desktop"><span>&nbsp;Preparando</span></i></a>
    <a asp-area="" asp-controller="Home" asp-action="Login"><i class="fas fa-sign-in-alt"><span>&nbsp;Login</span></i></a>
</div>